name: CI

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (optional)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        continue-on-error: true

      - name: Setup Python (optional)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
        continue-on-error: true

      - name: Install deps (if any)
        run: |
          if [ -f package.json ]; then npm ci; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint/Format (best-effort)
        run: |
          if [ -f package.json ]; then npm run -s lint || true; npm run -s format:check || true; fi
          if command -v flake8 >/dev/null 2>&1; then flake8 || true; fi
          if command -v black >/dev/null 2>&1; then black --check . || true; fi

      - name: Run tests
        run: |
          if [ -f package.json ]; then npm test --silent || true; fi
          if [ -f pyproject.toml ] || [ -f pytest.ini ] || [ -d tests ]; then pytest -q || true; fi

      - name: Coverage summary (if available)
        run: |
          if [ -f coverage.lcov ]; then echo "Found lcov"; fi
          if [ -f coverage.xml ]; then echo "Found XML"; fi
        continue-on-error: true
